name: tim_ui_kit
description: TUIKit 是基于 IM SDK 实现的一套 UI 组件,其包含会话、聊天、搜索、关系链、群组、音视频通话等功能。
version: 0.0.6-bugfix-1.0
homepage: https://cloud.tencent.com/product/im

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  tencent_im_sdk_plugin: ^3.9.2
  adaptive_action_sheet: ^2.0.1
  provider: ^6.0.1
  intl: ^0.17.0
  get_it: ^7.2.0
  dotted_border: ^2.0.0+2
  flutter_svg: ^1.0.0
  image_picker: ^0.8.4+4
  file_picker: ^4.2.3
  open_file: ^3.2.1
  super_tooltip: ^1.0.1
  video_player: ^2.2.10
  chewie: 1.1.0
  flutter_slidable: ^1.2.0
  flutter_plugin_record: ^1.0.1
  azlistview: ^2.0.0-nullsafety.0
  lpinyin: ^2.0.3
  transparent_image: ^2.0.0
  video_thumbnail: ^0.4.3
  permission_handler: ^8.3.0
  image_gallery_saver: ^1.7.1
  photo_view: ^0.13.0
  fluttertoast: ^8.0.8
  dio: ^4.0.4
  path_provider: ^2.0.8
  flutter_screenutil: ^5.1.0
  characters: ^1.1.0
  i18n: ^3.4.1
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.13
  json_annotation: ^4.4.0
  scroll_to_index: ^2.1.1
  connectivity_plus: ^2.2.0
  wechat_assets_picker: ^7.0.2
  wechat_camera_picker: ^3.0.1
  flutter_easyrefresh: ^2.2.1
  flutter_spinkit: ^5.1.0
  extended_image: ^6.0.2+1
  package_info_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: any
  fast_i18n: 5.12.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/
    - images/callingIcon/
    
    

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
